In [1]:
import numpy as np

# 数组创建

In [19]:
'''
   通过array
'''
#1维列表
lis = [1,2,3,4]
np.array(lis)

array([1, 2, 3, 4])

In [20]:
'''
   zeros 创建全0数组
'''
np.zeros(5) #生成一个包含5个元素的全0数组

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
'''
   empty 
'''
np.empty(7) #生成一个包含7个元素的 未初始化的

array([0., 0., 0., 0., 0., 0., 0.])

In [21]:
'''
   arange
'''
np.arange(1,5,2)  #设置2维怎么办？

array([1, 3])

In [22]:
'''
   linspace
'''
np.linspace(1,10,5) #等差数列

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [23]:
?np.linspace

In [24]:
'''
   logspace
'''
np.logspace(1,2,10) #等比数列

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [39]:
'''
   random 随机数列
'''
#生成0-1的随机数列
np.random.random(1)
np.random.random((3,3)) #生成2维

#生成平均分布
np.random.rand(10)
np.random.rand(3,3) #生成2维

#生成正太分布的样本
np.random.randn(10)
np.random.randn(3,3) #生成2维

#生成随机整数
np.random.randint(1,9,10) #start stop num
np.random.randint(1,9,(4,3,2)) #生成2维

array([[[8, 6],
        [8, 6],
        [5, 1]],

       [[1, 6],
        [4, 4],
        [2, 5]],

       [[2, 2],
        [6, 8],
        [8, 5]],

       [[3, 2],
        [2, 6],
        [6, 8]]])

# 创建数组

# 数组的属性

In [40]:
arr = np.random.randint(1,9,(3,3))
arr

array([[6, 5, 1],
       [1, 2, 6],
       [2, 6, 2]])

In [41]:
print('nidm',arr.ndim) #数组的轴的个数

nidm 2


In [42]:
print('shape',arr.shape) #数组的形状

shape (3, 3)


In [43]:
print('size',arr.size) #元素的个数

size 9


In [44]:
print('dtype',arr.dtype) 

dtype int64


In [45]:
print('itemsize',arr.itemsize) #字节大小

itemsize 8


# 数据类型

In [50]:
lis = [[1,2,3],[3,4,5]]
arr2 = np.array(lis) #默认自动推断
arr2

array([[1, 2, 3],
       [3, 4, 5]])

In [52]:
print(arr2.dtype)

int64


In [53]:
lis = [[1.1,2,3],[3,4,5]]
arr2 = np.array(lis) #默认自动推断
arr2

array([[1.1, 2. , 3. ],
       [3. , 4. , 5. ]])

In [54]:
print(arr2.dtype)

float64


In [57]:
#手动指定数据类型
lis = [[1,2,3],[3,4,5]]
arr2 = np.array(lis,dtype = np.float)
arr2

array([[1., 2., 3.],
       [3., 4., 5.]])

In [58]:
print(arr2.dtype)

float64


In [60]:
'''
   类型转换 astype
'''
lis = [[1,2,3],[3,4,5]]
arr2 = np.array(lis,dtype = 'int8')
arr2

array([[1, 2, 3],
       [3, 4, 5]], dtype=int8)

In [62]:
arr2 = arr2.astype('f4')
arr2

array([[1., 2., 3.],
       [3., 4., 5.]], dtype=float32)

# 修改形状

In [64]:
'''
   直接修改shape值
'''
arr3 = np.random.randint(1,9,(6,2))
arr3

array([[7, 5],
       [2, 7],
       [8, 2],
       [3, 6],
       [7, 6],
       [6, 3]])

In [65]:
arr3.shape

(6, 2)

In [66]:
#只要shape值得乘积不变可以修改
arr3.shape = (3,4)
arr3.shape

(3, 4)

In [67]:
arr3

array([[7, 5, 2, 7],
       [8, 2, 3, 6],
       [7, 6, 6, 3]])

In [68]:
'''
reshape
'''
arr4 = np.random.randint(1,9,(6,2))
arr4

array([[1, 4],
       [7, 8],
       [6, 2],
       [6, 7],
       [8, 1],
       [2, 3]])

In [70]:
arr4 = arr4.reshape(4,3)
arr4

array([[1, 4, 7],
       [8, 6, 2],
       [6, 7, 8],
       [1, 2, 3]])

In [76]:
arr5 = np.arange(12).reshape(-1,6) #系统自动推算
arr5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [78]:
'''
   降维操作
'''
arr6 = np.random.randint(1,9,(4,4,3))
arr6

array([[[4, 7, 2],
        [4, 2, 6],
        [8, 6, 4],
        [3, 6, 3]],

       [[1, 1, 5],
        [8, 4, 7],
        [6, 5, 8],
        [1, 6, 3]],

       [[5, 5, 4],
        [4, 1, 1],
        [1, 4, 3],
        [3, 2, 2]],

       [[3, 1, 1],
        [2, 4, 1],
        [5, 4, 8],
        [7, 6, 3]]])

In [80]:
arr6.reshape(-1,4)
arr6

array([[[4, 7, 2],
        [4, 2, 6],
        [8, 6, 4],
        [3, 6, 3]],

       [[1, 1, 5],
        [8, 4, 7],
        [6, 5, 8],
        [1, 6, 3]],

       [[5, 5, 4],
        [4, 1, 1],
        [1, 4, 3],
        [3, 2, 2]],

       [[3, 1, 1],
        [2, 4, 1],
        [5, 4, 8],
        [7, 6, 3]]])

In [82]:
arr6.reshape(-1)

array([4, 7, 2, 4, 2, 6, 8, 6, 4, 3, 6, 3, 1, 1, 5, 8, 4, 7, 6, 5, 8, 1,
       6, 3, 5, 5, 4, 4, 1, 1, 1, 4, 3, 3, 2, 2, 3, 1, 1, 2, 4, 1, 5, 4,
       8, 7, 6, 3])